Zms 2427 testing tobias fabian
it-at-m/eappointment pull request #512
Opened 2024-08-27 09:48 UTC by tobias74

2024-08-28 14:11 UTC, tobias74 commented
Closing this now in order to make a new branch with correct feature name and fixed tests.

2024-09-13 08:37 UTC, ThomasAFink requested changes

2024-09-13 13:27 UTC, Fabinatix97 commented on zmsapi/src/Zmsapi/MailTemplatesPreview.php
> +        //(new Helper\User($request))->checkRights('superuser');
Puh, das weiß ich gar nicht mehr. Soll ich es wieder aktiv setzen?

2024-09-13 13:30 UTC, ThomasAFink commented on zmsadmin/cache/.keep
> +
Sorry das kannst du behalten cache und .keep

2024-09-15 07:51 UTC, tobias74 commented on zmsapi/src/Zmsapi/MailTemplatesPreview.php
> +        //(new Helper\User($request))->checkRights('superuser');
Der Vollständigkeit halber sollte diese Überprüfung wohl wieder aktiv sein. Dieser Endpunkt gibt zwar aktuell nur Beispieldaten in den gerenderten EMail-Templates zurück, aber es gibt für andere Anwender hier keinen Verwendungsgrund. Man kann also argumentieren, dass dieser Endpunkt nur für Superuser erreichbar sein soll.

2024-09-15 07:56 UTC, tobias74 commented
> Why did you close it @tobias74 ?

I thought that we needed to create a new branch with the correct naming and ticket number :-) Otherwise this branch should be fine. There are a couple of experimental commits on this branch, so it probably should be squashed ;-)

2024-09-16 09:56 UTC, ThomasAFink approved these changes

2024-09-16 10:01 UTC, merged